<div class="row mt-5">
    <div class="col-md-10">
        <form action="/admin/manage-slider/add" method="post" id="add-slider-image-form" enctype="multipart/form-data">          
            
            <div class="row">               
                <div class="col-md-12 offset-md-2">
                    <input type="hidden" name="csrf" value="<?= $this->setCsrf() ?>">
                    <div class="text-danger mt-1"><?= $this->getErrorMessage('csrfError'); ?></div>
                </div>
            </div> 

            <div class="form-group row">             
                <label class="col-form-label col-md-2" for="file">Image:</label> 
                <div class="col-md-10">
                    <input type="file" name="file" id="file" class="filestyle">
                    <div class="text-danger mt-1"><?= $this->getErrorMessage('imageError'); ?></div>
                </div>
            </div>

            <div class="form-group row">
                <!-- &nbsp in order Public not to jump over to the next line when the width of the page is small -->
                <label class="col-sm-2 col-3" for="is_visible">Is&nbsp;Visible:</label> 
                <div class="col-sm-10 col-9">     
                    <label class="custom-control custom-checkbox">           
                          <input type="checkbox" class="custom-control-input" id="is_visible" name="is_visible" value="1">
                          <span class="custom-control-indicator"></span>
                          <span class="custom-control-description"></span>
                    </label>
                </div>
            </div>          

            <br>
            <div class="row">               
                <div class="col-md-12 offset-md-2">
                    <input type="submit" value="Submit" name="add_slider_image" class="btn btn-outline-primary">
                </div>
            </div>
            
        </form>
    </div>
</div>
