<div class="row mt-4">
    <div class="col-sm-12">
        <h4><?= $this->clearStr($this->getHeadTitle()) ?></h4>
        <hr> 
    </div>
</div>

<div class="row mt-4">
    <div class="col-sm-12">
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vitae risus finibus, laoreet erat vitae, elementum dolor. 
            Nam dignissim ullamcorper iaculis. Integer justo quam, mattis in ultrices ac, auctor a eros. Curabitur pretium posuere volutpat. 
            Phasellus lobortis fringilla enim, non fermentum ipsum facilisis vitae. Fusce malesuada nulla id justo fringilla interdum. 
            Morbi sodales magna sed risus auctor, vel sodales est laoreet. 
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. 
        </p>
        <p>
            Suspendisse aliquam consequat quam, vel aliquam mi aliquet non. Quisque augue tortor, congue blandit varius vel, pharetra vitae metus. 
            Morbi blandit massa sed ligula semper, ut egestas turpis scelerisque. Proin tristique a sem sit amet mattis. 
            Nulla porta felis eget porttitor elementum. Nunc a metus purus. Ut dolor magna, malesuada sit amet felis vitae, consequat malesuada massa. 
            Aliquam id porttitor justo. Vivamus ac lacus urna. Donec faucibus mauris velit, ut posuere ex feugiat at. 
            Sed porttitor rutrum enim, non porta dui pharetra nec. Donec non massa at massa fringilla dapibus a a sapien. 
            Quisque vel lobortis metus, in egestas elit.  
        </p>      
    </div>
</div>

<div class="row mt-5">
    <div class="col-sm-6">
        <div class="testimonial-card">
            <img src="/img/about-us/before-quote.png" alt="img" class="before-quote">
            <img src="/img/about-us/after-quote.png" alt="img" class="after-quote">
            <img src="/img/about-us/img-1.jpg" alt="img" class="testimonial-pic">
            <p class="testimonial">BN provides me the comfort of knowing that I can call, email, or write them about issues that might arise and will resolve them fairly, and to my satisfaction.</p>
            <p class="customer">John Price</p>
            <p class="location">Vancouver, WA</p>
        </div>
    </div>
    
    <div class="col-sm-6">
        <div class="testimonial-card">
            <img src="/img/about-us/before-quote.png" alt="img" class="before-quote">
            <img src="/img/about-us/after-quote.png" alt="img" class="after-quote">
            <img src="/img/about-us/img-2.jpg" alt="img" class="testimonial-pic">
            <p class="testimonial">BN provides me the comfort of knowing that I can call, email, or write them about issues that might arise and will resolve them fairly, and to my satisfaction.</p>
            <p class="customer">Sarah Price</p>
            <p class="location">Vancouver, WA</p>
        </div>
    </div>
</div>

<div class="row mt-4">
    <div class="col-sm-12">
        <p>
            Ut in eleifend erat. Morbi vestibulum, sem et pellentesque sagittis, tellus magna imperdiet augue, ac egestas purus mauris in sapien. 
            Sed dapibus fermentum laoreet. Sed vel fringilla ipsum, sed placerat nisl. Nam dapibus quis odio in volutpat. 
            Etiam a sem sit amet nulla imperdiet iaculis. Nam auctor, tellus id accumsan iaculis, erat sem aliquet lacus, sit amet mollis libero ante at felis. 
            Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed consequat elit orci, a elementum nibh rhoncus ut. 
            Sed volutpat tellus sagittis, cursus risus et, pharetra sapien. Duis a purus non nunc ultrices mollis. 
            Phasellus ultrices, sapien eu congue imperdiet, nibh enim porta leo, vitae dapibus orci elit sed velit. 
            Suspendisse sed pellentesque mauris, nec laoreet lorem. Etiam accumsan imperdiet nisi, a volutpat ligula. 
        </p>
        <p>
            Sed eget lacus convallis, dictum neque quis, mollis leo. Nam interdum velit at felis rutrum facilisis. 
            Curabitur at lorem pellentesque, mollis orci vestibulum, efficitur turpis. Donec ut mollis dolor. Etiam eu nisl justo. 
            Aenean sit amet bibendum est, sit amet euismod turpis. Donec eget odio augue. Nulla facilisi. 
            Maecenas nulla tortor, sollicitudin at nisi id, semper auctor est. Cras sed tortor imperdiet nisl rhoncus egestas.
            Etiam felis augue, interdum ut libero vel, scelerisque semper nunc. Donec vitae lectus nunc. Maecenas lacinia orci a felis pharetra rhoncus. 
        </p>
        <p>
            Etiam nunc lacus, dapibus vulputate blandit nec, consequat ut dui. Curabitur dui sapien, scelerisque in lacus ut, fermentum tempus mi. 
            Suspendisse imperdiet enim mi, vitae tincidunt mauris fringilla non. Donec interdum finibus interdum. Aenean tristique leo a malesuada dictum.
            Duis at purus in arcu cursus porttitor nec non dolor. Donec ut malesuada eros. Phasellus ultricies leo pellentesque pretium ultrices. 
        </p>
    </div>
</div>

<div class="row mt-5">
    <div class="col-sm-6">
        <div class="testimonial-card">
            <img src="/img/about-us/before-quote.png" alt="img" class="before-quote">
            <img src="/img/about-us/after-quote.png" alt="img" class="after-quote">
            <img src="/img/about-us/img-3.jpg" alt="img" class="testimonial-pic">
            <p class="testimonial">BN provides me the comfort of knowing that I can call, email, or write them about issues that might arise and will resolve them fairly, and to my satisfaction.</p>
            <p class="customer">Tom Price</p>
            <p class="location">Vancouver, WA</p>
        </div>
    </div>
    
    <div class="col-sm-6">
        <div class="testimonial-card">
            <img src="/img/about-us/before-quote.png" alt="img" class="before-quote">
            <img src="/img/about-us/after-quote.png" alt="img" class="after-quote">
            <img src="/img/about-us/img-4.jpg" alt="img" class="testimonial-pic">
            <p class="testimonial">BN provides me the comfort of knowing that I can call, email, or write them about issues that might arise and will resolve them fairly, and to my satisfaction.</p>
            <p class="customer">Jane Price</p>
            <p class="location">Vancouver, WA</p>
        </div>
    </div>
</div>

<div class="row mt-4">
    <div class="col-sm-12">
        <p>
            Ut in eleifend erat. Morbi vestibulum, sem et pellentesque sagittis, tellus magna imperdiet augue, ac egestas purus mauris in sapien. 
            Sed dapibus fermentum laoreet. Sed vel fringilla ipsum, sed placerat nisl. Nam dapibus quis odio in volutpat. 
            Etiam a sem sit amet nulla imperdiet iaculis. Nam auctor, tellus id accumsan iaculis, erat sem aliquet lacus, sit amet mollis libero ante at felis. 
            Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed consequat elit orci, a elementum nibh rhoncus ut. 
            Sed volutpat tellus sagittis, cursus risus et, pharetra sapien. Duis a purus non nunc ultrices mollis. 
            Phasellus ultrices, sapien eu congue imperdiet, nibh enim porta leo, vitae dapibus orci elit sed velit. 
            Suspendisse sed pellentesque mauris, nec laoreet lorem. Etiam accumsan imperdiet nisi, a volutpat ligula. 
        </p>      
        <p>
            Etiam nunc lacus, dapibus vulputate blandit nec, consequat ut dui. Curabitur dui sapien, scelerisque in lacus ut, fermentum tempus mi. 
            Suspendisse imperdiet enim mi, vitae tincidunt mauris fringilla non. Donec interdum finibus interdum. Aenean tristique leo a malesuada dictum.
            Duis at purus in arcu cursus porttitor nec non dolor. Donec ut malesuada eros. Phasellus ultricies leo pellentesque pretium ultrices. 
        </p>
    </div>
</div>

<div class="row mt-5">
    <div class="col-sm-6">
        <div class="testimonial-card">
            <img src="/img/about-us/before-quote.png" alt="img" class="before-quote">
            <img src="/img/about-us/after-quote.png" alt="img" class="after-quote">
            <img src="/img/about-us/img-5.jpg" alt="img" class="testimonial-pic">
            <p class="testimonial">BN provides me the comfort of knowing that I can call, email, or write them about issues that might arise and will resolve them fairly, and to my satisfaction.</p>
            <p class="customer">Jacob Price</p>
            <p class="location">Vancouver, WA</p>
        </div>
    </div>
    
    <div class="col-sm-6">
        <div class="testimonial-card">
            <img src="/img/about-us/before-quote.png" alt="img" class="before-quote">
            <img src="/img/about-us/after-quote.png" alt="img" class="after-quote">
            <img src="/img/about-us/img-6.jpg" alt="img" class="testimonial-pic">
            <p class="testimonial">BN provides me the comfort of knowing that I can call, email, or write them about issues that might arise and will resolve them fairly, and to my satisfaction.</p>
            <p class="customer">Emily Price</p>
            <p class="location">Vancouver, WA</p>
        </div>
    </div>
</div>

<div class="row mt-4">
    <div class="col-sm-12">
        <p>
            Aliquam pretium lacus eros, id sagittis nisl accumsan eu. Donec vel mauris lectus. Duis accumsan ante eu tempor lobortis.
            Sed tristique, mauris vitae hendrerit tempus, erat dui lacinia felis, convallis pulvinar felis dolor id neque. 
            Integer luctus fermentum nisl, ut porta dui dapibus vitae. Cras scelerisque congue lectus ac consequat.
            Vivamus dapibus quam vitae sem porttitor placerat. Quisque mi diam, viverra nec ultrices a, accumsan quis neque. Mauris ut vehicula sem.
            Pellentesque eleifend cursus massa ut cursus. Curabitur dignissim, ipsum in tempor posuere, felis ipsum vehicula est, et sodales tortor dui eget quam.
            Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum congue nibh velit, non venenatis lacus dignissim faucibus.
            Donec ultricies tempor risus rhoncus fermentum. Praesent faucibus viverra nibh, nec pulvinar felis malesuada semper. 
        </p>
        <p>
            Suspendisse aliquam consequat quam, vel aliquam mi aliquet non. Quisque augue tortor, congue blandit varius vel, pharetra vitae metus. 
            Morbi blandit massa sed ligula semper, ut egestas turpis scelerisque. Proin tristique a sem sit amet mattis. 
            Nulla porta felis eget porttitor elementum. Nunc a metus purus. Ut dolor magna, malesuada sit amet felis vitae, consequat malesuada massa. 
            Aliquam id porttitor justo. Vivamus ac lacus urna. Donec faucibus mauris velit, ut posuere ex feugiat at. 
            Sed porttitor rutrum enim, non porta dui pharetra nec. Donec non massa at massa fringilla dapibus a a sapien. 
            Quisque vel lobortis metus, in egestas elit.  
        </p>      
        <p>  
            In hac habitasse platea dictumst. Nullam tincidunt lectus ac lorem dapibus, nec porttitor dui tincidunt. 
            Pellentesque sed mi consequat, semper neque sed, sagittis elit. Donec ut tristique ipsum, vitae efficitur odio. 
            Maecenas varius consequat leo eget laoreet. Donec id sem eu velit laoreet ornare tempor tincidunt ipsum. 
            Sed et nisl vestibulum libero sodales tempor quis quis nisi. Quisque tellus libero, porta aliquam dignissim quis, pellentesque sit amet sem.
            Phasellus rutrum urna eu egestas tempus. Curabitur vitae metus pretium, venenatis erat quis, volutpat velit. 
            Aenean quis imperdiet libero, dignissim feugiat turpis. Integer semper consequat ultricies. 
        </p>      
    </div>
</div>

<div class="row mt-5">
    <div class="col-sm-6">
        <div class="testimonial-card">
            <img src="/img/about-us/before-quote.png" alt="img" class="before-quote">
            <img src="/img/about-us/after-quote.png" alt="img" class="after-quote">
            <img src="/img/about-us/img-7.jpg" alt="img" class="testimonial-pic">
            <p class="testimonial">BN provides me the comfort of knowing that I can call, email, or write them about issues that might arise and will resolve them fairly, and to my satisfaction.</p>
            <p class="customer">Matthew Price</p>
            <p class="location">Vancouver, WA</p>
        </div>
    </div>
    
    <div class="col-sm-6">
        <div class="testimonial-card">
            <img src="/img/about-us/before-quote.png" alt="img" class="before-quote">
            <img src="/img/about-us/after-quote.png" alt="img" class="after-quote">
            <img src="/img/about-us/img-8.jpg" alt="img" class="testimonial-pic">
            <p class="testimonial">BN provides me the comfort of knowing that I can call, email, or write them about issues that might arise and will resolve them fairly, and to my satisfaction.</p>
            <p class="customer">Sophia Price</p>
            <p class="location">Vancouver, WA</p>
        </div>
    </div>
</div>

<div class="row mt-4">
    <div class="col-sm-12">
        <p>
            Nunc pellentesque lorem in nisi elementum ornare. Cras ut iaculis lacus, non elementum neque. 
            Duis sollicitudin dui et enim malesuada, sed ultrices ex suscipit. Pellentesque porttitor bibendum fringilla. 
            Curabitur vitae massa in est placerat faucibus vitae eget libero. Nullam finibus cursus suscipit.
            Ut nibh metus, venenatis in dolor at, tincidunt accumsan dui. 
            Vestibulum iaculis, urna vel tristique suscipit, lorem odio dignissim tortor, ac ultricies leo purus eu eros. Aliquam et tellus mi. 
            Donec lorem sem, semper et mauris nec, mattis volutpat ligula. Morbi pharetra sapien a purus rutrum pretium. 
            Vivamus ac nibh et lorem pulvinar semper. Integer sagittis nisl eget urna laoreet, at commodo nulla efficitur.
            In nec consequat sem, in blandit nulla. In sed nunc ac nulla dignissim malesuada. Donec congue aliquet orci. 
        </p>
        <p>
            Suspendisse aliquam consequat quam, vel aliquam mi aliquet non. Quisque augue tortor, congue blandit varius vel, pharetra vitae metus. 
            Morbi blandit massa sed ligula semper, ut egestas turpis scelerisque. Proin tristique a sem sit amet mattis. 
            Nulla porta felis eget porttitor elementum. Nunc a metus purus. Ut dolor magna, malesuada sit amet felis vitae, consequat malesuada massa. 
            Aliquam id porttitor justo. Vivamus ac lacus urna. Donec faucibus mauris velit, ut posuere ex feugiat at. 
            Sed porttitor rutrum enim, non porta dui pharetra nec. Donec non massa at massa fringilla dapibus a a sapien. 
            Quisque vel lobortis metus, in egestas elit.  
        </p>      
        <p>  
            In hac habitasse platea dictumst. Nullam tincidunt lectus ac lorem dapibus, nec porttitor dui tincidunt. 
            Quisque mauris nibh, condimentum eget arcu eu, pellentesque sagittis est. 
            Donec placerat lectus quis porta facilisis. Nullam pellentesque blandit justo, id lobortis odio facilisis nec. 
            Vivamus laoreet viverra dolor, nec dictum nunc sagittis et. Phasellus dignissim lectus sed nunc dictum, semper consectetur leo ultricies. 
            Donec eget eros massa. Nam eros metus, placerat nec ante sed, imperdiet scelerisque magna.
            Donec sed risus vehicula, ultricies metus ac, tincidunt metus.  
        </p>      
        <p>   
            Vestibulum convallis consectetur tellus, sit amet mattis lectus porttitor eget. Aenean tincidunt ut turpis vitae accumsan. 
            Morbi quis cursus ipsum. Vivamus quis nibh a mauris blandit suscipit. Proin congue laoreet orci. Suspendisse luctus mollis tempor.
            Proin vestibulum finibus consectetur. In et enim in tellus aliquam egestas quis ut diam. 
            Fusce rutrum ipsum nec magna ultrices, a fringilla est malesuada. Donec eu sem lectus. 
            Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam rutrum nibh eget massa iaculis commodo. 
        </p>      
    </div>
</div>
       