<div class="row">
    
    <div class="col-lg-3">    
        <div class="fixed app-nav"><?= $categories; ?></div> <!-- Categories block -->
    </div>
    
    <div class="col-lg-9 articles-block"> 
        <div><img class="img-fluid rounded" src="<?= $this->entityDecode($article->image) ?>" alt="img"></div>
        <h2 class="mt-5 mb-3">
            <strong><?= $this->clearStr($article->title) ?></strong>
        </h2>
        <div><em>Published on <?= $this->getDateTime($article->date_time) ?></em></div>
        
        <!-- Block for ratings -->
        
        <div class="rating-wrapper">
            <form id="ratingsForm" data-avg="<?= $avgRaiting ?>" data-article-id="<?= $this->clearInt($article->id) ?>">
                <?php foreach (range(1, 5) as $value) : ?>

                <label>
                    <input type="radio" name="star" id="star<?= $value ?>" value="<?= $value ?>">
                    <i class="far fa-star" aria-hidden="true" name="star"></i>
                </label>

                <?php endforeach; ?>
            </form>
        </div>
        &nbsp;
        <span class="badge badge-primary" id="raitings-count"><?= $this->clearInt($raitingsCount) ?></span>&nbsp;&nbsp;
        <span id="already-rated"></span>
        
        <!-- Block for ratings -->
        
        <hr>
        <div><?= $this->entityDecode($article->content) ?></div>
        
        <hr class="my-5">
        <h4 class="mb-3">Comments</h4>

        <div id="new-comment" class="card bg-light">
            <div class="card-header">
                <h5 class="card-title"></h5>
                <hr class='comment-block-hr'>
                <span class="comment-data"><i class='fas fa-calendar-alt'></i></span>
            </div>
            <div id="comment-text" class="card-body"></div>
        </div>
        <br>
        <br>
        
        <div class="row">
            <div class="col-sm-12">  

                <form id="comment-form">
                    <input type="hidden" name="article-id" value="<?= $this->clearInt($article->id) ?>">

                    <div class="row">               
                        <div class="col-md-12 offset-md-2">
                            <input type="hidden" name="csrf" value="<?= $this->setCsrf() ?>">
                            <div class="text-danger my-2" id="csrfError"></div>
                        </div>
                    </div> 
                    
                    <div class="form-group row">
                        <label class="col-form-label col-md-2 asterisk" for="nickname">Nickname:</label> 
                        <div class="col-md-10">
                            <input id="nickname" type="text" name="nickname" class="form-control" required="required">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-md-2 asterisk" for="email">Email:</label> 
                        <div class="col-md-10">
                            <input id="email" type="email" name="email" class="form-control" required="required">
                            <div class="text-danger mt-1" id="emailError"></div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-md-2 asterisk" for="content">Content:</label>  
                        <div class="col-md-10">
                            <textarea id="content" name="content" class="form-control" required="required"></textarea>
                        </div>
                    </div>   

                    <br>
                    <div class="row">               
                        <div class="col-md-12 offset-md-2">
                            <input type="submit" value="Send" name="send-comment" class="btn btn-outline-primary">
                        </div>
                    </div>
                </form>

            </div>
        </div>

        <br>
        <hr>
        <br>

        <?php if (is_array($comments) && ! empty($comments)) : ?>
            <?php foreach ($comments as $comment) : ?>
        
                <div class="card bg-light">
                    <div class="card-header">
                        <h5 class="card-title"><i class="fas fa-user"></i> <?= $this->clearStr($comment->user_nickname) ?></h5>
                        <hr class='comment-block-hr'>
                        <span class="comment-data"><i class='fas fa-calendar-alt'>&nbsp;&nbsp;<?= $this->getDateTime($comment->entry_date) ?></i></span>
                    </div>
                    <div class="card-body"><?= $this->clearStr($comment->content, true) ?></div>
                </div>
                <br>
                <br>
        
            <?php endforeach; ?>
        <?php endif; ?>
 
    </div>
</div>
