<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">               
                <h4 class="modal-title" id="myModalLabel">Are You sure?</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger" id="delete-admin">Yes</button>
            </div>
        </div>
    </div>
</div>

<!-- Hidden form for delete admin -->
<form action="/admin/manage-admins/delete/<?= $this->clearInt($admin->id) ?>"
      method="post"
      class="modal-form"
>
    <input type="hidden" name="csrf" value="<?= $this->setCsrfArray($this->clearStr($admin->name)) ?>">
    <button type="button">Yes</button>
</form>

<div class="row mt-5">
    <?php if (!$admin) : ?>
    <div class="col-md-12">
        <h5>The list is empty</h5> 
    </div>
    <?php else : ?>
        <div class="col-md-10">
            <div><strong>Admin's name:</strong> &nbsp;&nbsp;&nbsp;<em><?= $this->clearStr($admin->name) ?></em></div>
            <div><strong>Email address:</strong> &nbsp;&nbsp;&nbsp;<em><?= $this->clearStr($admin->email) ?></em></div>
            <div><strong>Registration date:</strong> &nbsp;&nbsp;&nbsp;<em><?= $this->getDateTime($admin->registration_date, true) ?></em></div>
            <form action="/admin/manage-admins/edit/<?= $this->clearInt($admin->id) ?>" method="post" id="admin-edit-form">
                <div class="row">               
                    <div class="col-md-12 offset-md-2">
                        <input type="hidden" name="csrf" value="<?= $this->setCsrfArray($this->clearInt($admin->id)) ?>">
                        <div class="text-danger mt-1"><?= $this->getErrorMessage('csrfError'); ?></div>
                    </div>
                </div> 
                
                <div class="row form-group my-2">
                    <label class="col-1" for="role"><strong>Role:</strong></label> 
                    <div class="col-2">
                        <select name="role" class="form-control form-control-sm" id="role">             
                            <option value="admin" <?= ($this->clearStr($admin->role) == 'admin') ? 'selected' : ''?> >Admin</option>
                            <option value="super_admin" <?= ($admin->role == 'super_admin') ? 'selected' : ''?> >Super Admin</option>
                        </select>
                        <div class="text-danger mt-1"><?= $this->getErrorMessage('roleError'); ?></div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-5">
                        <hr>
                    </div>
                </div>
                <div class="row form-group">               
                    <div class="col-md-12">
                        <input type="submit" value="&nbsp;&nbsp;&nbsp;Edit&nbsp;&nbsp;&nbsp;" name="edit_admin" class="btn btn-outline-primary">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-2 text-right">
            <button type="button" data-toggle="modal" data-target="#myModal" class="btn btn-danger">
                Delete <?= str_replace('_', ' ', $this->clearStr($admin->role)) ?>
            </button>
        </div>
    <?php endif; ?>
</div>
