<div class="row">
    <div class="col-sm-12">
        <div class="mb-3">
            <a href="/admin/manage-admins/add" class="btn btn-outline-primary">Add admin</a>
        </div>
        
    </div>
    <?php if (! $admins) : ?>
    <div class="col-sm-12">
        <h5>The list is empty</h5> 
        <div class="message-box mt-2">
            <div class="text-success"><?= $this->getMessage('success') ?? ''; ?></div>
            <div class="text-danger"><?= $this->getMessage('error') ?? ''; ?></div>
        </div>
    </div>
    <?php else : ?>
    <div class="col-sm-12">
        <div class="message-box">
            <div class="text-success"><?= $this->getMessage('success') ?? ''; ?></div>
            <div class="text-danger"><?= $this->getMessage('error') ?? ''; ?></div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <tr>
                    <th>#</th>              
                    <th>Name</th>                  
                    <th>Email Address</th>                                     
                    <th>Role</th>
                    <th>Registration Date</th>
                    <th>Actions</th>
                </tr>
                <?php foreach ($admins as $admin) : ?>
                <tr>
                    <td><?= ++$cnt ?></td>
                    <td><?= $this->clearStr($admin->name) ?></td>
                    <td><?= $this->clearStr($admin->email) ?></td>
                    <td><?= $this->clearStr($admin->role) ?></td>
                    <td><?= $this->getDateTime($admin->registration_date) ?></td>
                    <td>
                        <a href="/admin/manage-admins/edit/<?= $this->clearInt($admin->id) ?>">Edit</a>                      
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <?php endif; ?>
</div>
