<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title><?= $this->getHeadTitle() ?></title>

        <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        <link rel="stylesheet" type="text/css" href="/css/jquery-filestyle.min.css">
        <link rel="stylesheet" type="text/css" href="/css/j-confirm-action.css">       
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" >
        
        
      
        <script type="text/javascript" src="/js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="/js/popper.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/js/app-script.js"></script>
        <script type="text/javascript" src="/js/bootstrap.bundle.min.js"></script>
        <script type="text/javascript" src="/js/jquery-filestyle.min.js"></script>
        <script type="text/javascript" src="/js/scriptbreaker-multiple-accordion-1.js"></script>
        <script type="text/javascript" src="/js/j-confirm-action.js"></script>
       
    </head>
    <body>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="/">Breaking News</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mr-auto">                         
                        <li class="nav-item">
                            <a class="nav-link" href="/about-us">About Us</a>
                        </li>  
                        <li class="nav-item">
                            <a class="nav-link" href="/contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/portfolio">Portfolio</a>
                        </li>
                        
                        <?php if ($this->isIssetAdmin()) : ?>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin">Admin</a>
                        </li>
                        <?php endif; ?>
                        
                    </ul>
                    <form action="/search" method="get" class="form-inline" id="navbar-search">   
                        <input type="text" name="search" class="form-control form-control-sm" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-secondary btn-sm"  type="submit">Go!</button>
                        </span>
                    </form>
                </div>
            </div>
        </nav>
        
        <div class="container">
            <?php $this->template() ?>
        </div>    

        <footer class="bg-dark footer">
            <div class="container">

                <div class="row text-center">    
                    <ul class="col-lg-12 list-inline" id="social-acons-block">
                        <li class="list-inline-item">
                            <a href="https://twitter.com/<?= $this->fileGetContent('soc-icons/twitter.txt'); ?>" target="_blank">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://facebook.com/<?= $this->fileGetContent('soc-icons/facebook.txt'); ?>" target="_blank">
                                <i class="fab fa-facebook"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://youtube.com/<?= $this->fileGetContent('soc-icons/youtube.txt'); ?>" target="_blank">
                                <i class="fab fa-youtube"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                
                <div class="row text-center">
                    <div class="col-lg-12 text-white " id="footer-text-content"><?= $this->fileGetContent('footer/footer-text.txt'); ?></div>
                </div>
                    
            </div>    
        </footer>

        <a id="back-to-top" 
            href="#" 
            class="btn btn-primary btn-sm back-to-top" 
            role="button"                       
            data-placement="left">
            <i class="fas fa-arrow-alt-circle-up fa-2x"></i>
        </a>
    </body>
</html>
