<div class="row">
    
    <div class="col-lg-3">    
        <div class="fixed app-nav"><?= $categories; ?></div> <!-- Categories block -->
    </div>

    <div class="col-lg-9">
        
        <?php if ($slider) : ?>
        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
                <?php foreach ($slider as $key => $item) : ?>
                    <li data-target="#carouselExampleIndicators" data-slide-to="<?= $this->clearInt($key) ?>"></li>
                <?php endforeach; ?>
            </ol>
            <div class="carousel-inner" role="listbox">
                <!-- In 'app-script.js' added class 'active' to first slider's element ( without it slider will not work )  -->              
                <?php foreach ($slider as $item) : ?>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="<?= $this->clearStr($item->image) ?>" alt="slider image">
                    </div>
                <?php endforeach; ?>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <?php endif; ?>

        <div class="card-columns">            

            <?php if (! $articles) : ?>
                <div class="col-sm-12">
                    <h5>The list is empty</h5> 
                </div>
            <?php else : ?>
                <?php foreach ($articles as $article) : ?>

                    <div class="card-content">
                        <div class="card">
                            <img class="card-img-top img-fluid img-thumbnail app-thumbnail" src="<?= $this->clearStr($article->image) ?>" alt="Card image cap">
                            <div class="card-body">
                                <h4 class="card-title"> <a href="/page/<?= $this->clearInt($article->id) ?>"><?= $this->clearStr($article->title) ?></a></h4>
                                <p class="card-text"><?= $this->entityDecode($article->description) ?></p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">
                                    <a href="/page/<?= $this->clearInt($article->id) ?>" class="btn btn-primary btn-sm">Read more</a>
                                </small>
                            </div>
                        </div>
                    </div>

                <?php endforeach; ?>
            <?php endif; ?>

        </div>

        <hr>
        <br>
        <div class="text-center">
            <a href="#" id="loadMore" onclick="return false" class="btn btn-outline-primary btn-lg btn-block">
                Load More &nbsp;<i class="fas fa-arrow-down"></i>
            </a>
        </div>

    </div>
</div>