<script src="/js/ckeditor.js"></script>
<script>
    $(function(){ ClassicEditor.create( document.querySelector( '#editor' ) ).catch( error => {console.error( error );} ); });
</script>
<div class="row mt-5">
    <div class="col-md-10">
        <form action="/admin/manage-articles/add" method="post" id="add-article-form" enctype="multipart/form-data">          
            
            <div class="row">               
                <div class="col-md-12 offset-md-2">
                    <input type="hidden" name="csrf" value="<?= $this->setCsrf() ?>">
                    <div class="text-danger mt-1"><?= $this->getErrorMessage('csrfError'); ?></div>
                </div>
            </div> 

            <div class="form-group row">
                <label class="col-form-label col-md-2 asterisk" for="title">Title:</label> 
                <div class="col-md-10">
                    <input id="title" type="text" name="title" class="form-control" required="required">
                    <div class="text-danger mt-1"><?= $this->getErrorMessage('titleError'); ?></div>
                </div>
            </div>
                       
            <div class="form-group row">
                <label class="col-form-label col-md-2 asterisk" for="title">Categories:</label> 
                <div class="col-md-10">
                    <select class="form-control selectpicker" name="category_id">                    
                        <?php foreach ($categories as $category) : ?>
                        <option value="<?= $category->id; ?>"><?= $category->name; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            
            <div class="form-group row">
                <label class="col-form-label col-md-2 asterisk" for="description">Description:</label>  
                <div class="col-md-10">
                    <textarea id="description" name="description" class="form-control" required></textarea>
                </div>
            </div>   
            
            <div class="form-group row">
                <label class="col-form-label col-md-2 asterisk" for="editor">Content:</label> 
                <div class="col-md-10">
                    <textarea name="content" id="editor" class="form-control" ></textarea>
                    <div class="text-danger mt-1" id="editor-message"></div>
                </div>
            </div>  

            <div class="form-group row">             
                <label class="col-form-label col-md-2" for="file">Image:</label> 
                <div class="col-md-10">
                    <input type="file" name="file" id="file" class="filestyle">
                    <div class="text-danger mt-1"><?= $this->getErrorMessage('imageError'); ?></div>
                </div>
            </div>

            <div class="form-group row">
                <!-- &nbsp in order Public not to jump over to the next line when the width of the page is small -->
                <label class="col-sm-2 col-3" for="is_public">Is&nbsp;Public:</label> 
                <div class="col-sm-10 col-9">     
                    <label class="custom-control custom-checkbox">           
                          <input type="checkbox" class="custom-control-input" id="is_public" name="is_public" value="1">
                          <span class="custom-control-indicator"></span>
                          <span class="custom-control-description"></span>
                    </label>
                </div>
            </div>          

            <br>
            <div class="row">               
                <div class="col-md-12 offset-md-2">
                    <input type="submit" value="Submit" name="add_article" class="btn btn-outline-primary">
                </div>
            </div>
            
        </form>
    </div>
</div>