<br>
<div>
    <h4><?= $this->clearStr($this->getHeadTitle()) ?></h4>
    <hr>    
</div>

<div class="row mt-5">
    <div class="col-md-10">
        <form action="/login" method="post" id="login-form">          
            
            <div class="row">               
                <div class="col-md-12 offset-md-2">
                    <input type="hidden" name="csrf" value="<?= $this->setCsrf() ?>">
                    <div class="text-danger mt-1"><?= $this->getErrorMessage('csrfError'); ?></div>
                </div>
            </div> 

            <div class="form-group row">
                <label class="col-form-label col-md-2 asterisk" for="email">Email:</label> 
                <div class="col-md-10">
                    <input id="login" type="email" name="email" class="form-control" required="required">
                    <div class="text-danger mt-1"><?= $this->getErrorMessage('emailError'); ?></div>
                </div>
            </div>
            
            <div class="form-group row">
                <label class="col-form-label col-md-2 asterisk" for="password">Password:</label> 
                <div class="col-md-10">
                    <input id="password" type="password" name="password" class="form-control" required="required">
                    <div class="text-danger mt-1"><?= $this->getErrorMessage('doNotMatch'); ?></div>
                </div>
            </div>
                      
            <div class="form-group row">
                <!-- &nbsp in order Public not to jump over to the next line when the width of the page is small -->
                <label class="col-sm-2 col-3" for="remember_me">Remember me:</label> 
                <div class="col-sm-10 col-9">     
                    <label class="custom-control custom-checkbox">           
                          <input type="checkbox" class="custom-control-input" id="remember_me" name="remember_me" value="1">
                          <span class="custom-control-indicator"></span>
                          <span class="custom-control-description"></span>
                    </label>
                </div>
            </div>          

            <br>
            <div class="row">               
                <div class="col-md-12 offset-md-2">
                    <input type="submit" value="Submit" name="login" class="btn btn-outline-primary">
                </div>
            </div>
            
        </form>
    </div>
</div>
