<div class="row mt-4">
    <div class="col-sm-12">
        <h4><?= $this->clearStr($this->getHeadTitle()) ?></h4>
        <hr> 
    </div>
</div>

<div class="row">
    <div class="col-md-4 my-4">
        <div class="portfolio"  title="Simplesite" data-toggle="tooltip" data-placement="bottom">
            <a href="http://simplesite.96.lt" target="_blank">
                <img src="/img/portfolio/simplesite.png"
                     alt="site-image"                    
                     class="img-fluid img-rounded"
                >
            </a>
        </div>
    </div>
    <div class="col-md-4 my-4">
        <div class="portfolio" title="Jokeshop" data-toggle="tooltip" data-placement="bottom">
            <a href="http://jokeshop.96.lt" target="_blank">
                <img src="/img/portfolio/jokeshop.png"
                     alt="site-image"
                     class="img-fluid img-rounded"
                >
            </a>
        </div>
    </div>
    <div class="col-md-4 my-4">
        <div class="portfolio" title="Socnetwork" data-toggle="tooltip" data-placement="bottom">
            <a href="http://socnetwork.96.lt" target="_blank">
                <img src="/img/portfolio/socnetwork.png"
                     alt="site-image"
                     class="img-fluid img-rounded"
                >
            </a>
        </div>
    </div>
</div>
